NEXT-10072 - Refactor for 6.3
shopware/swag-docs-extend-page pull request #2
Opened 2020-08-27 13:07 UTC by jakob-kruse

2020-08-31 07:30 UTC, klarstil approved these changes

2020-09-02 06:08 UTC, mitelg requested changes

2020-09-02 06:08 UTC, mitelg commented on src/Resources/test/e2e/.gitignore
> +w# Logs
please only put the needed things here

2020-09-02 07:20 UTC, marcelbrode submitted a review, later dismissed
Notice Telgis comment and I'm fine, too :)

2020-09-07 09:51 UTC, marcelbrode approved these changes

2020-09-07 10:06 UTC, mitelg approved these changes

2020-09-07 10:06 UTC, merged